//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан генератором.
//     Время создания: 09.03.2026
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны
//     при повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProxyManager.Properties
{
	using System;
	using System.Drawing;
	using System.Globalization;
	using System.Resources;

	/// <summary>
	///   Класс ресурса со строгой типизацией для поиска локалилизованных ресурсов.
	/// </summary>
	[global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
	[global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
	[global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
	internal class Resources
	{
		private static global::System.Resources.ResourceManager resourceMan;
		private static global::System.Globalization.CultureInfo resourceCulture;

		[global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
		internal Resources()
		{
		}

		/// <summary>
		///   Возвращает кэшированный экземпляр ResourceManager.
		/// </summary>
		[global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
		internal static global::System.Resources.ResourceManager ResourceManager
		{
			get
			{
				if (object.ReferenceEquals(resourceMan, null))
				{
					global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ProxyManager.Properties.Resources", typeof(Resources).Assembly);
					resourceMan = temp;
				}
				return resourceMan;
			}
		}

		/// <summary>
		///   Переопределяет свойство CurrentUICulture текущего потока.
		/// </summary>
		[global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
		internal static global::System.Globalization.CultureInfo Culture
		{
			get
			{
				return resourceCulture;
			}
			set
			{
				resourceCulture = value;
			}
		}

		/// <summary>
		///   Возвращает локализованный ресурс типа System.Drawing.Icon.
		/// </summary>
		internal static System.Drawing.Icon globe
		{
			get
			{
				object obj = ResourceManager.GetObject("globe", resourceCulture);
				return ((System.Drawing.Icon)(obj));
			}
		}
	}
}
